### ISSUE TITLE
Core build with some added functions breaks on older browsers (on upgrade 4.11.1 -> 4.13.1)

### ISSUE THREAD

**Issue by tepez** [lodash/lodash-cli#110]
Our custom lodash build is

    lodash core --development plus=add,assign,capitalize,cloneDeep,deburr,findIndex,forIn,intersection,isError,isPlainObject,merge,method,pickBy,property,range,remove,times,uniq,values,String,maxBy,isNil,chunk

As you can see in [this diff](https://gist.github.com/tepez/a4da104a2793840e6b65e3043684c88b/revisions#diff-261720f5cadc69a8d1b18547049737afL914), the built-in reference for Symbol, Map, etc are present in the 4.11.1 build, but are no longer present on the 4.13.1 build.

This causes reference errors on browsers without these, e.g. Mobile Safari 8, Chrome mobile 34, because [Symbol](https://gist.github.com/tepez/a4da104a2793840e6b65e3043684c88b/revisions#diff-261720f5cadc69a8d1b18547049737afR797) and [Map](https://gist.github.com/tepez/a4da104a2793840e6b65e3043684c88b/revisions#diff-261720f5cadc69a8d1b18547049737afR1247) are still referenced.

**Comment by jdalton** [comment]
Hi @tepez!

This issue is resolved in our edge bits and will be out with the next bump.
