### ISSUE TITLE
Actually deprecate lodash.contains on npm

### ISSUE THREAD

**Issue by ChALkeR** [lodash/lodash-cli#120]
[lodash-contains](https://www.npmjs.com/package/lodash.contains) has 6567 downloads/month, which is not that high, compared to 76263 for `lodash.includes` and 32555679 for `lodash`.

Its readme says that it's deprecated in favour of [lodash-includes](https://www.npmjs.com/package/lodash.includes), but the npm package wasn't deprecated and prints no deprecation warning upon installation, and users could miss the info in the readme.

The issue is that I saw new modules that started using `lodash.contains` not so long ago, e.g. `js-libp2p-swarm`: https://github.com/libp2p/js-libp2p-swarm/commit/0fa14c9608ea45aad9dff0e1b8880dd45989c12a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R60

Deprecating the package on npm would give a clear indication that it's not going to be supported and that should not be used in new projects.

**Comment by jdalton** [comment]
Thanks, done!

**Comment by jdalton** [comment]
By the way, similar deps as `lodash.contains`,  just inlined.

**Comment by ChALkeR** [comment]
Thanks!

> By the way, similar deps as `lodash.contains`, just inlined.

Yes, I assumed so, it's the number of packages and metadata that slows down the things a bit on install time =).

**Comment by jdalton** [comment]
I rather folks measure projects by other metrics like that it's well tested, robust, etc.

**Comment by jdalton** [comment]
I've seen too many deps throw more meaning metrics out the window in search of shallow deps.

**Comment by ChALkeR** [comment]
@jdalton But it's clearly not that case here =).
