### ISSUE TITLE
Export to global different then _

### ISSUE THREAD

**Issue by makbol** [lodash/lodash-cli#122]
I was trying to use: `lodash include=debounce moduleId=_my exports=global` but it exports only in case of modules (amd, commonjs). I would like to make custom build which exports lodash to global as e.g `_my` instead of `_`.

**Comment by jdalton** [comment]
Hi @makbol!

You can use the [iife command](https://lodash.com/custom-builds) to accomplish this:
```shell
lodash iife="(function(window,undefined){%output%;root._my=_}(this))"
```

**Comment by makbol** [comment]
Thank you @jdalton :+1:
