### ISSUE TITLE
exports=es & exports=npm not working

### ISSUE THREAD

**Issue by julienetie** [lodash/lodash-cli#128]
When I try:
```cli
lodash include=isArray,isElement exports=umd
```

I get:
```cli
Invalid `exports` entry passed: es
```

lodash --help shows:
```cli
  exports=..   Comma separated values of ways to export lodash.
               (i.e. “amd”, “es”, “global”, “node”, “none”, “npm”, & “umd”)
```

The same applies for _npm_ unless I'm missing something obvious.

**Comment by jdalton** [comment]
Hi @julienetie!

I can't repro on `lodash-cli@4.16.4`. 

```shell
lodash include=isArray,isElement exports=umd
```
produces a build.

**Comment by julienetie** [comment]
Oh, I made a bit of a mistake, didn't mean to put umd above, should have been **es** :
```
lodash include=isArray,isElement exports=es
```
I re-installed lodash-cli@4.16.4 , and I still have the same issue.

**Comment by jdalton** [comment]
The `es` command only works with the `modularize` command.

**Comment by julienetie** [comment]
Thanks, I've just seen it in the notes now.
