### ISSUE TITLE
lodash-cli v4.17.1 won't terminate

### ISSUE THREAD

**Issue by mk-pmb** [lodash/lodash-cli#132]
From [my debug log](https://github.com/mk-pmb/mini-lodash-v004-pmb/blob/master/build/debug-lodash-cli.log), generated by [this script](https://github.com/mk-pmb/mini-lodash-v004-pmb/blob/master/build/debug-lodash-cli.js), it looks like a `java -jar …` call from a shrinkwrapped dependency clings to a dead child process. (Dead = doesn't show up in `ps u $PID` while nodejs is still waiting.)

Node.js v6.9.1, npm v3.10.8, Ubuntu 14.04.5 LTS trusty, google-closure-compiler version: "20150901.0.0"

**Comment by jdalton** [comment]
The `lodash-cli` will use Google Closure Compiler if Java is available. If you're having problems with it then you might want to check into Closure Compilers FAQ. I can't repro any issue with it and our CI runs still pass.
