### ISSUE TITLE
throttle method not included with include="throttle"

### ISSUE THREAD

**Issue by hejmartin** [lodash/lodash-cli#137]
I'm running `lodash core include="throttle"`, but the generated file doesn't include the `throttle` method. If I leave out the `core` argument, the method is included. 

Output: https://gist.github.com/hejmartin/97497f02c63f51a89efc32db9b095b92

I'm using lodash-cli@4.17.4 and node 6.6.0 on a Mac.

Am I doing something wrong?

**Comment by jdalton** [comment]
Correct. The `core` argument restricts to a set of core methods. You should be able to combo it with `plus="throttle"` though.

**Comment by hejmartin** [comment]
Aha, yes, it seems to be working. Thanks!
