### ISSUE TITLE
Add notice about deprecated categories

### ISSUE THREAD

**Issue by d10** [lodash/lodash-cli#24]
When I ran

```bash
$ lodash compat category=functions
```

I received a message that it was invalid. I then remembered that this has been changed to a non-plural form function for Lo-Dash v3.0. You should probably add a note that it is deprecated and inform that of the proper usage if they specify a plural category.

**Comment by jdalton** [comment]
Instead I'm going to just support category aliases so devs can continue to type the old category names and they'll work. I'll close this issue once it's checked in.

**Comment by jdalton** [comment]
Patched [here](https://github.com/lodash/lodash-cli/commit/4f90986aa92ac00352429a6fd09bdb84c7098b7e).
