### ISSUE TITLE
Update travis tests with 6to5 instead of es6-module-transpiler

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash-cli#30]
Should we update our [travis tests](https://github.com/lodash/lodash-cli/blob/defadb53e0282348febc8ee521a6dc503dce784c/.travis.yml#L59) with [6to5](https://www.npmjs.com/package/6to5) instead of [es6-module-transpiler](https://www.npmjs.com/package/es6-module-transpiler).
Related to the blog post "[6to5 + esnext](http://6to5.org/blog/2015/01/12/6to5-esnext/)".

 \cc @thejameskyle

**Comment by thejameskyle** [comment]
es6-module-transpiler and 6to5 still are fairly separate projects (6to5 doesn't do any bundling). I'll defer to @eventualbuddha on this though.

**Comment by jdalton** [comment]
> es6-module-transpiler and 6to5 still are fairly separate projects (6to5 doesn't do any bundling)

We don't bundle for testing, just `-f commonjs`, so I think this would map to  [6to5 src --out-dir lib](http://6to5.org/docs/usage/cli/#compile-directories). I'll see tonight. Also excited to see the [common](https://github.com/6to5/6to5.github.io/blob/master/docs/usage/modules.md#formats) formatter sugar!

**Comment by jdalton** [comment]
I'll run both for now, can't hurt ensuring our es6 build works in multiple transpilers. I'll revisit dropping es6-module-transpiler as the merge shakes out.

**Comment by thejameskyle** [comment]
> We don't bundle for testing, just -f commonjs

Oh it should work for your use case then, I was making assumptions about what you were doing.

**Comment by eventualbuddha** [comment]
Probably safe to just do 6to5 for CommonJS. If you want to bundle e.g. for production I suggest using http://esperantojs.org/, as I'll but putting my module efforts there.

**Comment by jdalton** [comment]
Closed via https://github.com/lodash/lodash-cli/commit/b035129b62e0fef83b747a746f1fae220e507da4.
