### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by Naddiseo** [lodash/lodash-cli#31]
I expect this could also be a problem with my environment, but running lodash from cli complains about invalid arguments. The current HEAD has my issue fixed thanks to #26.

```
$ npm install lodash-cli
lodash-cli@2.4.2 node_modules/lodash-cli
├── lodash@2.4.1
├── glob@3.2.7 (inherits@2.0.1, minimatch@0.2.14)
├── uglify-js@2.4.6 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.43)
└── closure-compiler@0.2.3
$ lodash modularize

Invalid arguments passed: nodejs, /home/thing/projects/static/node_modules/.bin/lodash
For more information type: lodash --help

```

Would it be possible to publish a new revision release with the fix to #26 in included?

**Comment by jdalton** [comment]
Hi @Naddiseo! Thanks for the heads up. A new release should be coming soonish.
