### ISSUE TITLE
3.0 Backbone Build

### ISSUE THREAD

**Issue by ChiperSoft** [lodash/lodash-cli#32]
Now that `underscore` and `backbone` are no longer available presets, what combination of arguments do I need to use to create a backbone compatible version of lodash 3?

**Comment by jdalton** [comment]
I knew I forgot to address something in the release notes. I'll tackle this in a few.

**Comment by jdalton** [comment]
Looks like I won't have time over lunch however I'll answer it here in the meantime.

Since our last release, 2.4.1, Underscore has aligned significantly with loash so the need for a separate compat build has diminished. If you still need compatibility we recommend leveraging modules in lodash v3 either by way of `require('lodash/lang/cloneDeep')` or `require('lodash.clonedeep')` to supplement your Underscore use.

**Comment by ChiperSoft** [comment]
So if I understand you correctly, you're saying that I can just use a standard vanilla lodash 3 build and it'll work fine with backbone?  If so, that's good news, I wasn't aware things had lined up that well.

However, what I liked about the backbone build was that it only included the functions that backbone needed, and we could then selectively include ala carte anything that we wanted beyond that base feature set.  It kept the file size down (our 2.4.1 build was only 22k minified, vs 3.0's 49k minified)

If you can provide a build configuration to achieve that, I'd be very appreciative.

**Comment by jdalton** [comment]
Here is the list of method deps from [lodash-cli 2.4.1](https://github.com/lodash/lodash-cli/blob/2.4.1/bin/lodash#L485-L544). You can use that to generate a custom build or require them individually as in `lodash.map` or as part of the `lodash` module, `require('lodash/collection/map')`.

**Comment by ChiperSoft** [comment]
John, your require examples are completely useless for frontend devs who aren't using commonjs loaders and just need it to keep working in the browser :)

Thank you for the link, I should be able to work out a build from that.

**Comment by jdalton** [comment]
> John, your require examples are completely useless for frontend devs who aren't using commonjs loaders and just need it to keep working in the browser :)

You can use the [AMD build](https://github.com/lodash/lodash/tree/3.0.0-amd) too :smile_cat:

**Comment by jdalton** [comment]
@ChiperSoft Nice [gist](https://gist.github.com/ChiperSoft/6aa4e7a17833c3c4cb2d) for creating a Backbone build! You can reduce it some by removing `lodash`, `wrapperChain`, `wrapperValue`, and possibly `chain` as `value` should cover those.

**Comment by ChiperSoft** [comment]
Good to know, thanks!

**Comment by jdalton** [comment]
Also the `modern` build is closer to the old `underscore` build than `compat`.
