### ISSUE TITLE
lodash fails with exit code 0

### ISSUE THREAD

**Issue by dbo** [lodash/lodash-cli#33]
Running lodash with an invalid parameter exits with code 0, e.g.
```bash
$ lodash --foo

Invalid argument passed: --foo
For more information type: lodash --help
$ echo $?
0
```
This affects e.g. `grunt-lodash` as well, which will report a green build, even in case of a broken config.

(FWIW: I noticed this problem with the incompatible change `--debug -> --development`).

**Comment by jdalton** [comment]
Ah good catch. Thanks!

**Comment by jdalton** [comment]
\cc @phated Should we really `process.exit(1)` with invalid arguments or should we throw an error so others can catch it? How will this affect grunt-lodash?

**Comment by phated** [comment]
I don't think it effects us either way.  `process.exit` doesn't work right on windows, I believe.

**Comment by jdalton** [comment]
Ok cool. I was looking at [this post](http://www.nczonline.net/blog/2014/02/04/maintainable-node-js-javascript-avoid-process-exit/). It also breaks out unit tests so I'll switch to throwing an error that we and others can catch.
