### ISSUE TITLE
Output copyright header first when outputting in STDOUT

### ISSUE THREAD

**Issue by d10** [lodash/lodash-cli#35]
On Heroku for lodash-webbuilder, requests timeout after around 30 seconds. Sometimes when there are multiple requests made, it might take longer than that to generate lodash. Is it possible to output the copyright header first so Heroku will know that there is still content upcoming, while the lodash build is being minified etc., thus preventing them from stopping the request and showing an error page.

**Comment by jdalton** [comment]
Is it just needing output? I can add a throbber like I have for the unit tests to keep something moving on the console.

**Comment by jdalton** [comment]
Would that do?

**Comment by jdalton** [comment]
Ah no this is for STDOUT so a throbber wouldn't do. Not sure sending the copyright first will do much but I can try.

**Comment by jdalton** [comment]
Actually could you simply cache the created file for the given build that way it's created once and then you just pass the generated file if it's already made. You can construct the name from version+commands then like md5 it or smth (@mathiasbynens may have a better naming convention)

**Comment by d10** [comment]
True, but that cache wouldn't scale far if it's in memory, and would also
be cleared everyone an update was pushed.

**Comment by mathiasbynens** [comment]
Even if caching was implemented, requests with custom `iife` wrappers cannot really be cached since there is literally an infinite number of possibilities there. Outputting the license header comment early would avoid the issue. Could you reconsider the wontfix label please?

**Comment by jdalton** [comment]
> Even if caching was implemented, requests with custom iife wrappers cannot really be cached since there is literally an infinite number of possibilities there.

I'm fine with that, those are pretty edge.

**Comment by jdalton** [comment]
@d10 
> True, but that cache wouldn't scale far if it's in memory, and would also be cleared everyone an update was pushed.

The cache wouldn't be in memory. Clearing on bumps is fine.

**Comment by jdalton** [comment]
> Outputting the license header comment (or any portion of it) early would avoid the issue. Could you reconsider the wontfix label please?

Would it? It wouldn't hurt to try.

**Comment by jdalton** [comment]
If it's writing to a file then there would be no stdout. So then he could implement a throbber. Right?

**Comment by d10** [comment]
> The cache wouldn't be in memory.

What kind is cache are you referring to? I was thinking something like:

```js
var cache = {};
cache[request.query] = code;
```

  > Outputting the license header comment (or any portion of it) early
would avoid the issue.

You could maybe just output `/**` first.

**Comment by jdalton** [comment]
You generate a file on disk. That's the kind of cache I'm talking about.

**Comment by d10** [comment]
Ah, that works too. Currently we just pipe the content from STDOUT to the response.

**Comment by mathiasbynens** [comment]
Pre-compile every possible version of lodash (locally, before publishing) and save it to disk using a predictable file name format. Then lodash-cli only needs to be invoked on the server for special `iife` requests.

**Comment by jdalton** [comment]
> Pre-compile every possible version of lodash (locally, before publishing) and save it to disk using a predictable file name format. Then lodash-cli only needs to be invoked on the server for special iife requests.

@kangax did this for smth if I remember correctly.

**Comment by jdalton** [comment]
On the STDOUT bit is it the minifying that's the slow down, currently the copyright header is generated at the very end before passing to the minifier.

**Comment by d10** [comment]
There would also be cases like the `include` option where it might be a far fetch to pre-compile everything.

**Comment by jdalton** [comment]
A combo of pre-compile and cache as it goes should be fine.

**Comment by kangax** [comment]
Yes, I did this a while ago; created static build files of all possible permutations of fabric.js — https://github.com/kangax/fabricjs.com/tree/gh-pages/build/files

It's a nightmare.

With 5-8 modules or so, it's not that bad, but we're now at 14 and with 2^14 (16,384) files, it's impossible to work with almost any tool:

- github were concerned that repo is taking few gigabytes
- github can't even show all the files in a dir now (if you go there)
- sublime can barely handle working with such repo
- jekyll takes forever to start when working with this repo
- even all-powerful git takes forever for something as simple as `git stash` or checkout

My plan now is to build these files dynamically on a client (I didn't do it because I wanted to utilize our node.js build script and it jsut seemed like a neat idea at the time).
