### ISSUE TITLE
Chain returns undefined in 3.2.x

### ISSUE THREAD

**Issue by john-kurkowski** [lodash/lodash-cli#37]
When piecemeal including chaining, a chain like `_(foo).sortBy('bar').pluck('id')` works with lodash-cli 3.1.1. However in 3.2.0, `_(foo)` returns `undefined`.

Relevant head of the build output:

```
 * lodash 3.1.0 (Custom Build) <https://lodash.com/>
 * Build: `lodash --development --output ./vendor/lodash.custom.js modern exports="global,node" include="chain,pluck,sortBy"`
```

**Comment by d10** [comment]
Are you running this on Node.js/io.js or browser?

**Comment by john-kurkowski** [comment]
Node.js 0.10.36

Thanks for closing this so quick! I look forward to trying out the next release.
