### ISSUE TITLE
Allow choosing which minifier to use

### ISSUE THREAD

**Issue by demoneaux** [lodash/lodash-cli#40]
Closure Compiler seems to take a long time to generate files on the [lodash-webbuilder dev site](http://lodash-webbuilder-dev.herokuapp.com/). By choosing which minifer to use, we can avoid this issue.

**Comment by d10** [comment]
Ping? ;)

**Comment by jdalton** [comment]
PR it.

**Comment by jdalton** [comment]
Closing as `wontfix` for now though I'm still open to PRs.
