### ISSUE TITLE
Category for Backbone methods

### ISSUE THREAD

**Issue by TheFuzzball** [lodash/lodash-cli#41]
I'm creating a custom lodash build for a Backbone project, I'm having to define all backbone methods one-by-one as an include. It would be very useful to me, and others that make custom builds of lodash for Backbone, to be able to specify backbone methods as a category.

**Comment by d10** [comment]
For now, you can try [this command](https://gist.github.com/ChiperSoft/6aa4e7a17833c3c4cb2d). Related to #32.

**Comment by jdalton** [comment]
Backbone ends up using a lot of the API so saving won't be that dramatic. The gist @d10 links to is a good way to tackle it. You can also add methods to it if you want others than those required by Backbone.
