### ISSUE TITLE
Incorrect `Build: ` header in lodash.js when IIFE option contains equal sign

### ISSUE THREAD

**Issue by cspotcode** [lodash/lodash-cli#43]
Tiny bug: when I invoke lodash-cli as follows:
```
lodash exports=none iife=";(function(){%output%; root.lodash = _}.call(this))" --source-map
```
it generates a LoDash comment header like so:
```
/**
 * @license
 * lodash 3.10.0 (Custom Build) <https://lodash.com/>
 * Build: `lodash exports="none" iife=";(function() {%output%; root.lodash " --source-map`
```
Note the truncated IIFE option.

I think this is the code that causes the bug.  It splits the IIFE option on equal signs, dropping anything after the second equal sign.
https://github.com/lodash/lodash-cli/blob/master/bin/lodash#L137

**Comment by jdalton** [comment]
Thanks @cspotcode!
