### ISSUE TITLE
Split option parsing into separate file

### ISSUE THREAD

**Issue by demoneaux** [lodash/lodash-cli#5]
Currently, I feel that the lodash bin file is too large. Placing argument parsing logic into the bin file and shifting the actual build tools into say lib/build.js will help. Also that will allow other scripts like grunt-lodash to use it programmatically if you expose an API.

**Comment by InstyleVII** [comment]
Started to dive in and wanted to know a good way to break things up. Do you want a module file for each and every top level function or are there groupings I should be looking for / composing myself? It makes sense for the first two top level functions as they are quite large. When you scroll down though (~line 1479) you start having a lot of small functions. I felt that giving each one it's own .js file might be getting a little module crazy. Let me know what you think, I can look into grouping them by some logic or another.

**Comment by InstyleVII** [comment]
Also fair to point out a lot of those functions all start with "Removes..." and then later on "Replaces..." so that might be a grouping. I'll keep parsing the code.

**Comment by d10** [comment]
This is a hard one. Personally I think lodash-cli is far too big and
complicated. It would be good to at least get somewhere with this though ;)

**Comment by jdalton** [comment]
>  I felt that giving each one it's own .js file might be getting a little module crazy. Let me know what you think, I can look into grouping them by some logic or another.

Ya you can group them into groups for `dep`, `function`, `var`, `src`, and so on to start.

**Comment by jdalton** [comment]
I've started working on this. I'm roughly 60% through splitting out everything into modules. I expect to wrap this up this week.

**Comment by jdalton** [comment]
Closing since this project will be discontinued in Lodash v5.
