### ISSUE TITLE
Add support for FP to modularize

### ISSUE THREAD

**Issue by nmn** [lodash/lodash-cli#77]
loads 4 looks awesome! But FP and modules are not exclusive.

**Comment by jdalton** [comment]
lodash-cli is really about slicing the monolithic lodash.js up into parts. The `fp` additions are wrappers around the existing lib. As such support for modularized `fp` is being added over https://github.com/lodash/lodash/pull/1779 instead.

**Comment by GRUBES** [comment]
I see that the linked PR has been merged already, but I'm not sure I understand how to put it to use. I'd like to do with `fp` exactly what `lodash modularize exports=amd` does for `core`. Is this currently possible?

**Comment by jdalton** [comment]
The current method would be to use webpack, browserify, rollup or other bundler to generate a bundle without using an AMD loader.

**Comment by GRUBES** [comment]
@jdalton Appreciate the quick response, as usual!

Unfortunately I have no control over the loader as I work on a third-party SaaS platform that hides all the loading from us. The only format it will read is AMD =/

**Comment by jdalton** [comment]
Then use the dist versions of `lodash.s` and the `lodash.fp.js`.
See https://github.com/lodash/lodash/wiki/FP-Guide#installation.

**Comment by jdalton** [comment]
It's not modular but that's the option you've got.

**Comment by jdalton** [comment]
@GRUBES The [fp convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) could be used to convert lodash amd modules but it would need to be built for the browser (bundled).
