### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by nwhite89** [lodash/lodash-cli#81]
Hi I am trying to update https://github.com/rockabox/ng-lodash to be the latest version of lodash however, `lodash-cli` is returning an error about the exports and modern being set. The repo does use `grunt-lodash` however, I have tried the following using just `lodash-cli`

Copying from the documentation for custom builds:
```sh
lodash modern minus=result,shuffle

Invalid argument passed: modern
For more information type: lodash --help
```

```sh
lodash iife="!function(window,undefined){%output%}(this)"

-bash: !function: event not found
```

Any ideas would be great cheers

**Comment by jdalton** [comment]
The `modern` modifier is no longer valid for lodash-cli v4 as it's always modern.

**Comment by nwhite89** [comment]
@jdalton regarding `iife`?

**Comment by jdalton** [comment]
That `iife` issue doesn't look related to lodash-cli. It looks like your bash is interpreting what's in your quotes as some kind of command.

**Comment by jdalton** [comment]
I've updated the site to remove the `modern` reference and escape the `!` in the command example which fixes the issue in zsh.

**Comment by nwhite89** [comment]
awesome thanks @jdalton
