### ISSUE TITLE
The lodash 4.4.0 modularize build caused lodash.pick@4.0.1 to break

### ISSUE THREAD

**Issue by alavers** [lodash/lodash-cli#85]
My project had a dependency on `lodash.pick` pinned to version 4.0.1, however it broke recently, as it fell out of sync with its `lodash._baseflatten` dependency, when both had been bumped up to 4.1.0. `lodash.pick` gets generated with a loose version selector for that dependency: `^4.0.0`:

https://github.com/lodash/lodash/blob/npm-packages/lodash.pick/package.json#L18

That explains why the two modules fell out of sync, and while updating `lodash.pick` to 4.1.0 fixes the issue, looking into it it appears lodash-cli chooses these loose version selectors.

https://github.com/lodash/lodash-cli/blob/master/bin/lodash#L284

Is this intentional? Or is it just unsafe to pin to specific versions of modularized lodash modules?

**Comment by jdalton** [comment]
We should pin internals to `~`.

**Comment by jdalton** [comment]
This requires a bit more work to do properly. I'll need to do two passes and sort private dependencies ascending by number of dependencies.

**Comment by jdalton** [comment]
Tackled more https://github.com/lodash/lodash-cli/commit/9c2ac4b3c965b63288d414a48b831b4fc870d5a8.

**Comment by jdalton** [comment]
I've bumped and published the packages with `~` for internal packages.
