### ISSUE TITLE
Add option to emit preprocessed non-minified output

### ISSUE THREAD

**Issue by trkjgrdg** [lodash/lodash-cli#88]
When using lodash in a project compiled by the Closure Compiler in advanced mode, it makes sense to use a non-minified version of lodash, and minify the whole project (including lodash) together.  This way one can use lodash like "\_.filter(" instead of like "\_['filter'](" without messing with externs.

So the request is for lodash-cli to be able to emit non-minified code suitable for use with the Closure Compiler in advanced mode.  This probably means passing the code through preprocess, but not property-escaping the user-facing API.

**Comment by jdalton** [comment]
I don't really recommend folks use Closure Compiler advanced mode on their own. It takes a lot of hand holding so it doesn't break things.

**Comment by jdalton** [comment]
Because of the extra work and relatively little gain I may end up pulling Closure Compiler use altogether.
