### ISSUE TITLE
Custom build always assigned to global `_` variable?

### ISSUE THREAD

**Issue by tkambler** [lodash/lodash-cli#98]
Consider the following example:

```
lodash \
    include=each,map,filter \
    exports=node \
    -o lodash.custom.js \
    -p
```

I would expect the generated module to only export itself via `module.exports`, but instead - I see this:

```
(freeWindow || freeSelf || {})._ = lodash;
```

A previously loaded version of lodash gets clobbered in the process. Is the appropriate solution to immediately call `_.noConflict()` after lodash my custom lodash build (which would have to be updated to include the `noConflict()` method)?

**Comment by jdalton** [comment]
Your export target is `node` so that won't hit.

**Comment by jdalton** [comment]
On second thought, patched https://github.com/lodash/lodash-cli/commit/4a8f0fcb5064f900b3a4298be816d2e76fb08a2e.

**Comment by tkambler** [comment]
Yeah, I wasn't quite sure what you meant by your last comment.
